---
dory:
  dnsmasq:
    enabled: true
    domains:
    -
      domain: docker
      address: 172.17.0.1
    -
      domain: dev
      address: 172.17.0.1
    container_name: dory_dnsmasq
    port: 53
    kill_others: ask
    service_start_delay: 5
  nginx_proxy:
    enabled: true
    container_name: dory_dinghy_http_proxy
    https_enabled: false
    ssl_certs_dir: ''
  resolv:
    enabled: true
    nameserver: 172.17.0.1
    port: 53
  debug: 
